### ISSUE TITLE
Web browser in VNM fails to render some webpages

### ISSUE THREAD

**Issue by civier** [NeuroDesk/neuromachine#23]
Tom Johnstone from Swinburne will look into this. He says it is a known problem with web browsers accessed via VNC.

**Comment by stebo85** [comment]
Solved :) We found out that it's possible to add more shm space in docker. VS code had the same problem. Solution is to start with more shm:

sudo docker run --shm-size=1gb -it --privileged --name neuromachine -v ~/vnm:/vnm -e USER=user -p 8080:8080 vnmd/neuromachine:20210826
